FROM rcs/haskell:9.4 as builder

# FROM rcs/haskell-brittany:8.10.1

FROM haskell:9.4

MAINTAINER Hamilton 

RUN mkdir -p /root/.local/bin

COPY --from=builder /root/.local/bin/hpack /root/.local/bin/hpack

RUN apt update 

RUN apt -y install libgsl0-dev libghc-postgresql-libpq-dev libicu-dev libtinfo-dev 

ENTRYPOINT ["/bin/bash"]

