#!/bin/bash

DOCKER_IMG="rcs/elm-test:0.19"

TMP="/home/rcs/opt/elmcommon"

docker run --user $(id -u):$(id -g) -it --rm -v "$(pwd):/code" -v "$TMP:/tmp" -w "/code" -e "HOME=/tmp" $DOCKER_IMG "$@"

exit 0
