#!/bin/bash

LOC="rcs"

# docker run -it --rm -v /home/"$1"/opt:/home/"$1"/opt -v /home/"$1"/.cabal:/root/.cabal "$1"/haskell:1.0  
docker run -it --rm -v /home/"$LOC"/opt:/home/"$LOC"/opt -v /home/"$LOC"/.cabal:/root/.cabal "$LOC"/haskell:8.2

exit 0


