#!/bin/bash

usage()
{
cat << EOF
usage: $0 options

OPTIONS:
   -h      Show this message
   -v      Haskell image version. Default: 8.4
   -r      Run as root
EOF
}

HASKELL_VER="rcs/haskell:8.6.5"
# HASKELL_VER="rcs/haskell:8.6"
ROOT="0"
while getopts “hrv:” OPTION
do
     case $OPTION in
         h)
             usage
             exit 1
             ;;
         r)
             ROOT="1"
             ;;
         v)
             HASKELL_VER=$OPTARG
             ;;
         ?)
             usage
             exit
             ;;
     esac
done


#if [[ -z "$1" ]]; then
#    echo "Using default Haskell version: $HASKELL_VER"
#else
#    HASKELL_VER="$1"
#fi

if [ "$ROOT" = "1" ]; then
  docker run --name haskell1 -it --rm -v /home/rcs/opt:/home/rcs/opt -v /home/rcs/opt/.stack:/root/.stack $HASKELL_VER
  # docker run --name haskell1 -it --rm -v /home/rcs/opt:/home/rcs/opt $HASKELL_VER
else
  docker run --name haskell1 --user $(id -u):$(id -g) -it --rm -v /home/rcs/opt:/home/rcs/opt $HASKELL_VER
fi

echo $HASKELL_VER

exit 0
