#!/bin/bash

JS="$1"

 echo "Running $(pwd)/$JS..."

# docker run -i --rm --cap-add=SYS_ADMIN --name puppeteer-chrome alekzonder/puppeteer node -e "`cat example.js`"

docker run --shm-size 1G --rm -v $(pwd)/app -v $(pwd)/$JS:/app/index.js alekzonder/puppeteer:latest

# docker run -e XAUTHORITY=/root/.Xauthority -e DISPLAY=$DISPLAY --shm-size 1G --rm -v $(pwd)/app -v $(pwd)/$JS:/app/index.js alekzonder/puppeteer:latest


exit 0
