#!/bin/bash

LOCAL_VOL=/home/"$1"/database/dockervolumes/postgres/data

PG_VER=""$1"/postgres:1.0"

docker run --name postgres_hilo -v  $LOCAL_VOL:/var/lib/postgresql/data -e POSTGRES_PASSWORD=ok -p 5432:5432 -d $PG_VER

echo $LOCAL_VOL

exit 0


