#!/bin/bash

PG_VER=9.6.2

LOCAL_VOL=/media/"$1"/ed11bb40-d507-4568-ac47-d61f406759f6/dockervolumes/postgres/data

# LOCAL_VOL=/var/lib/postgresql/data

docker run --name postgres2 -v  $LOCAL_VOL:/var/lib/postgresql/data -e POSTGRES_PASSWORD=ok -p 5432:5432 -d postgres:$PG_VER

echo $LOCAL_VOL

exit 0


