
FROM python:3.8.1-slim-buster

# MAINTAINER Hamilton 

LABEL org.opencontainers.image.authors="Hamilton"

RUN pip install --upgrade pip

RUN pip install yfinance --upgrade --no-cache-dir

WORKDIR /etradejanitor


